### ISSUE TITLE
onNextMonth and onPrevMonth are required

### ISSUE THREAD

**Issue by septagram** [Hanse/react-calendar#15]
Sounds like there's an obvious default action for `onNextMonth` and `onPrevMonth`: to show the next or previous month respectively.

Would be great if they were not required.

**Comment by Hanse** [comment]
Great idea. I added an `onChangeMonth` for this in v1.2.0.

**Comment by septagram** [comment]
@Hanse Here, this would make all the props optional. So e.g., just `<Calendar />` should work for the common use case. By default, the month buttons would scroll calendar to previous and next month.

Would you accept it?
