### ISSUE TITLE
Range select

### ISSUE THREAD

**Issue by mweibel** [Hanse/react-calendar#17]
Hi,

first of all thanks for this super simple and to the point calendar component. After trying a whole bunch of other available packages I finally found something which isn't bloated with a billion features and still can be easily extended.
My use case is a range select. I've implemented this feature with only very little amount of code by wrapping your Calendar in a stateful component. 
As I think this could be a use case also for other people, I thought of making that component separate from my application and release it as open source. 
Would you rather:
a) Accept a PR adding this functionality as a separate component?
b) Keep that repository as is and I'll create a separate package having a dependency on your package

I honestly have a slight preference for option b because it would keep react-calendar as simple as it is right now. I just added option a because I'm a bit too lazy at the moment to setup all the build stuff for it 😄 

Therefore, what would you prefer?

**Comment by Hanse** [comment]
Hi!

Thanks! As you suggest I'd like to keep this as focused as it is now. I'm reluctant to add new features at the moment and would also prefer option b). I'd be happy to add a link to your project though 🎉

**Comment by mweibel** [comment]
Great! I thought so :)
Will let you know as soon as I have something. 
I'll probably create a PR soon though for a new feature: display below the header the weekdays. Obviously configurable etc :)
